services:
  filebrowser:
    image: gtstef/filebrowser:stable
    volumes:
      - /pool:/pool # Do not use a root "/" directory or include the "/var" folder
      - /srv/remotemount:/srv/remotemount
      - /pool/docker/filebrowserquantum/config.yaml:/home/filebrowser/data/config.yaml:ro
      - /pool/docker/filebrowserquantum/data:/home/filebrowser/data
    ports:
      - 8042:80
    restart: unless-stopped