services:
  bentopdf:
    # Using Docker Hub
    image: bentopdfteam/bentopdf-simple:latest
    # Or using GitHub Container Registry
    # image: ghcr.io/alam00000/bentopdf-simple:latest
    container_name: bentopdf
    ports:
      - '8000:8080'
    restart: unless-stopped