services:
  noah-mqtt:
    image: ghcr.io/mtrossbach/noah-mqtt:latest
    container_name: noah-mqtt
    environment:
      - GROWATT_USERNAME=${GROWATT_USERNAME}
      - GROWATT_PASSWORD=${GROWATT_PASSWORD}
      - MQTT_HOST=192.168.1.24
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    restart: unless-stopped