services:
  arcane-agent:
    image: ghcr.io/getarcaneapp/arcane-headless:latest
    container_name: arcane-agent
    restart: unless-stopped
    environment:
      - AGENT_MODE=true
      - EDGE_TRANSPORT=poll
      - AGENT_TOKEN=${AGENT_TOKEN} 
      - MANAGER_API_URL=${MANAGER_API_URL}
      - PUID=1000
      - PGID=100
    ports:
      - "3553:3553"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /pool/docker/arcane-agent/data:/app/data
      - /pool/compose:/app/data/projects
