services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - /pool/docker/esphome/config:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    #devices:
      # if needed, add esp device(s) as in command line examples above
      #- /dev/ttyUSB0:/dev/ttyUSB0
      #- /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
    restart: always